import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexProviderClient } from "@/components/providers/convex-provider";
import { ThemeProvider } from "next-themes";
import CulturalPattern from "@/components/site/CulturalPattern";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConvexProviderClient>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <CulturalPattern />
            <main className='min-h-[70vh]'>{children}</main>
          </ThemeProvider>
        </ConvexProviderClient>
      </body>
    </html>
  );
}
